finetuning_type: full

num_train_epochs: 1
max_steps: -1
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
lr_scheduler_type: cosine
weight_decay: 0.1
warmup_ratio: 0.1

precision: bf16
deepspeed_stage: 2

logging_steps: 10
save_steps: 500
eval_steps: 500
