finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_target: all
lora_dropout: 0.05

num_train_epochs: 1
max_steps: -1
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 3.0e-4
lr_scheduler_type: cosine
weight_decay: 0.1
warmup_ratio: 0.1

precision: bf16
deepspeed_stage: 2

logging_steps: 10
save_steps: 500
eval_steps: 500
