import argparse
import json
import os
import subprocess
from pathlib import Path

from rich.panel import Panel
from rich.progress import (
    Progress, SpinnerColumn, BarColumn, TextColumn,
    MofNCompleteColumn, TimeElapsedColumn,
)
from rich.table import Table

from src import console

DATA_DIR = os.environ.get("DATA_DIR", "/data")
REPO_ID = "bghira/pseudo-camera-10k"
REPO_URL = f"https://huggingface.co/datasets/{REPO_ID}"


def fmt_size(nbytes: int) -> str:
    if nbytes >= 1 << 30:
        return f"{nbytes / (1 << 30):.1f} GB"
    if nbytes >= 1 << 20:
        return f"{nbytes / (1 << 20):.1f} MB"
    if nbytes >= 1 << 10:
        return f"{nbytes / (1 << 10):.1f} KB"
    return f"{nbytes} B"


def clone_repo(clone_dir: Path, hf_token: str = None):
    if (clone_dir / ".git").exists():
        console.print(f"  [green]cached[/green]  [dim]{clone_dir}[/dim]")
        return

    clone_dir.mkdir(parents=True, exist_ok=True)

    url = REPO_URL
    if hf_token and hf_token != "your_token_here":
        url = f"https://hf_user:{hf_token}@huggingface.co/datasets/{REPO_ID}"

    with console.status("[bold]Cloning repository...[/bold]", spinner="dots"):
        env = os.environ.copy()
        env["GIT_LFS_SKIP_SMUDGE"] = "0"
        subprocess.run(
            ["git", "clone", "--depth=1", url, str(clone_dir)],
            check=True,
            env=env,
        )
    console.print(f"  [green]cloned[/green]  [dim]{clone_dir}[/dim]")


def load_pseudo_camera(num_samples: int, output_file: str):
    output_path = Path(output_file)
    if output_path.exists():
        line_count = sum(1 for _ in open(output_path, encoding="utf-8"))
        if line_count >= num_samples:
            info = Table.grid(padding=(0, 2))
            info.add_column(style="dim")
            info.add_column()
            info.add_row("file", str(output_path))
            info.add_row("pairs", f"{line_count:,}")
            info.add_row("size", fmt_size(output_path.stat().st_size))

            console.print(Panel(
                info,
                title="[green]Skipped -- already exists[/green]",
                border_style="dim",
                padding=(1, 2),
            ))
            return

    console.print(Panel(
        f"[bold]{REPO_ID}[/bold]\n\n"
        "~10K synthetic photographs with detailed captions "
        "generated by SDXL + LLaVA.\n"
        "[dim]Each sample is a PNG image paired with a text caption. "
        "Used for VLM fine-tuning.[/dim]",
        title="[bold]Dataset[/bold]",
        border_style="dim",
        padding=(1, 2),
    ))

    hf_token = os.environ.get("HF_TOKEN")
    if not hf_token or hf_token == "your_token_here":
        console.print("  [yellow]warn[/yellow]  HF_TOKEN not set")
    else:
        console.print("  [green]auth[/green]  HF_TOKEN")

    clone_dir = Path(os.environ.get("HF_HOME", f"{DATA_DIR}/.cache")) / "pseudo-camera-10k"
    clone_repo(clone_dir, hf_token)

    image_dir = clone_dir / "train"
    caption_dir = clone_dir / "caption"

    image_files = {f.stem: f for f in image_dir.glob("*.png")}
    caption_files = {f.stem: f for f in caption_dir.glob("*.txt")}

    common_stems = sorted(set(image_files) & set(caption_files))

    stats = Table.grid(padding=(0, 2))
    stats.add_column(style="dim")
    stats.add_column(justify="right")
    stats.add_row("images", f"{len(image_files):,}")
    stats.add_row("captions", f"{len(caption_files):,}")
    stats.add_row("matched", f"[green]{len(common_stems):,}[/green]")
    console.print(stats)

    if not common_stems:
        raise ValueError("No matched image-caption pairs found")

    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    total = min(len(common_stems), num_samples) if num_samples else len(common_stems)
    saved = 0
    skipped = 0

    with open(output_path, "w", encoding="utf-8") as fout, \
         Progress(
             SpinnerColumn(),
             TextColumn("{task.description}"),
             BarColumn(bar_width=40),
             MofNCompleteColumn(),
             TimeElapsedColumn(),
             console=console,
         ) as progress:
        task = progress.add_task("Pairing", total=total)
        for stem in common_stems:
            if num_samples and saved >= num_samples:
                break

            caption = caption_files[stem].read_text(encoding="utf-8").strip()
            if not caption:
                skipped += 1
                progress.advance(task)
                continue

            record = {
                "image": str(image_files[stem]),
                "caption": caption,
            }
            json.dump(record, fout, ensure_ascii=False)
            fout.write("\n")
            saved += 1
            progress.advance(task)

    console.print(f"  [green]{saved:,}[/green] pairs saved to [dim]{output_file}[/dim]")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=int, default=int(os.environ.get("DATA_SAMPLES", 10000)))
    parser.add_argument("--output", type=str, default=f"{DATA_DIR}/pseudo-camera-raw.jsonl")
    args = parser.parse_args()
    load_pseudo_camera(args.samples, args.output)


if __name__ == "__main__":
    main()
